server:
  port: 8080

spring:
  application:
    name: api-gateway
  profiles:
    active:
      - dev
  config:
    import: optional:configserver:http://localhost:8888/
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
#      default-filters:
#        - TokenRelay
#  security:
#    oauth2:
#      resourceserver:
#        jwt:
#          issuer-uri: http://127.0.0.1:53704/realms/sweetify
#  security:
#    oauth2:
#      client:
#        registration:
#          gateway:
#            provider: keycloak
#            client-id: sweetify_client
#            client-secret: OYLRtJ0Ozg9CvSBkdwRuxZJZnbbxrROn
#            authorization-grant-type: authorization_code
#            redirect-uri: "http://localhost:8080/login/oauth2/code/{registrationId}"
#            scope: openid
#        provider:
#          keycloak:
#            issuer-uri: "http://127.0.0.1:53704/realms/sweetify"

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
