server:
  port: 8080

spring:
  application:
    name: api-gateway
  profiles:
    active:
      - dev
  cloud:
    gateway:
      routes:
        - id: commands
          uri: http://ms-commands:8080/
          predicates:
            - Path=/commands/**
        - id: products
          uri: http://ms-products:8080/
          predicates:
            - Path=/products/**
        - id: ingredients
          uri: http://ms-products:8080/
          predicates:
            - Path=/ingredients/**
        - id: stock
          uri: http://ms-stock:8080/
          predicates:
            - Path=/stock/**
